import './globals.css';
import "swiper/css";
import 'swiper/css/navigation';
import 'swiper/css/pagination';


export const metadata = {
  title: 'Nest - Grocery Store Ecommerce Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />

      <body>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
